
[facebook]
access_token = "EAAKbDUncZBTYBPXQc3PJepvEp06LYZBFLUQcMZC4sy279WRC3mbgvKH9pE75SmqVE6Gtzaakl7edvGzu9hzN5WAZA9U0HVB91rVe9h8zM3R3vYFXNR6HfFiM54k1jkGqiSo2HEv6xkAysfEwxX3NNXSQacAps1blZCM8f96JFW7wFGZAQdG8XxyFGWgZAF46Qm24pzj5ZAfmSu7VwMLUwb9nOa6hX4gqrNZCKcCLh7QZC8"
ad_account_id = "act_1593231484495476"

# Conta do CV
[cv_leads]
subdomain = "selectbroker"
email = "keltonpereira@lucianocavalcante.com.br"
token = "e7846550b75064d326db22638e46971d788774e5"  # token da API de leads

[cv_atendimento]
subdomain = "selectbroker"
email = "keltonpereira@lucianocavalcante.com.br"
token = "7801d013218c2949ce9a8edad37105b135749a77"  # token da API de atendimentos

[cv_cliente]
subdomain = "selectbroker"
email = "keltonpereira@lucianocavalcante.com.br"
token = "e96c4e8b11ef58efd338fe932d99d17e0416feb2"  # token da API de atendimentos

[cv_corretor]
subdomain = "selectbroker"
email = "keltonpereira@lucianocavalcante.com.br"
token = "9d4190db9745ffe73ba8d6e385b06fd9cddda5d8"  # token da API de atendimentos

[cv_empreendimento]
subdomain = "selectbroker"
email = "keltonpereira@lucianocavalcante.com.br"
token = "80f178745f17b88a90ff8988e0a590e7174c02da"  # token da API de atendimentos

[cv_etapa]
subdomain = "selectbroker"
email = "keltonpereira@lucianocavalcante.com.br"
token = "8dbcbe303d67bbe862247ccf6644c57b09808145"  # token da API de atendimentos